# Generated by Django 2.1.2 on 2018-12-24 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Accountholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('userimageurl', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('emailid', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200, null=True)),
                ('kpaccountname', models.CharField(max_length=200)),
                ('bankname', models.CharField(max_length=200, null=True)),
                ('bankacnumber', models.CharField(max_length=100, null=True)),
                ('ifcscode', models.CharField(max_length=100, null=True)),
                ('accountstatus', models.CharField(max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('socialtype', models.CharField(max_length=200, null=True)),
                ('socialtypetoken', models.CharField(max_length=200, null=True)),
                ('securitycode', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_Accountholders',
            },
        ),
        migrations.CreateModel(
            name='tbl_Adminuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('userimageurl', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('userstatus', models.CharField(max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('permission', models.CharField(max_length=100, null=True)),
                ('securitycode', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_Adminuser',
            },
        ),
        migrations.CreateModel(
            name='tbl_CompetitionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('finishdate', models.DateTimeField()),
                ('starttime', models.CharField(max_length=100, null=True)),
                ('endtime', models.CharField(max_length=100, null=True)),
                ('finishtime', models.CharField(max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('createby', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_competitiondetails',
            },
        ),
        migrations.CreateModel(
            name='tbl_ComplaintDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postuserid', models.CharField(max_length=100, null=True)),
                ('complainby', models.CharField(max_length=100, null=True)),
                ('postownername', models.CharField(max_length=100, null=True)),
                ('posttitle', models.CharField(max_length=100, null=True)),
                ('complaindesc', models.CharField(max_length=500, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('compuserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_Accountholders')),
            ],
            options={
                'db_table': 'tbl_complaintdetails',
            },
        ),
        migrations.CreateModel(
            name='tbl_ImageTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('templateimageurl', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('createdate', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_imagetemplates',
            },
        ),
        migrations.CreateModel(
            name='tbl_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationtitle', models.CharField(max_length=100)),
                ('notificationdesc', models.CharField(max_length=500, null=True)),
                ('notificationtype', models.CharField(max_length=200, null=True)),
                ('assignto', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='tbl_PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptname', models.CharField(max_length=100)),
                ('compttitle', models.CharField(max_length=100, null=True)),
                ('posttile', models.CharField(max_length=100)),
                ('postimageurl', models.CharField(max_length=200, null=True)),
                ('winnername', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100, null=True)),
                ('bacnkname', models.CharField(max_length=100, null=True)),
                ('acnumber', models.CharField(max_length=100, null=True)),
                ('ifcscode', models.CharField(max_length=100, null=True)),
                ('rewardamount', models.IntegerField(null=True)),
                ('refernceid', models.CharField(max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('comptid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_ComplaintDetails')),
            ],
            options={
                'db_table': 'tbl_paymentdetails',
            },
        ),
        migrations.CreateModel(
            name='tbl_PoetComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('postcomments', models.CharField(max_length=500, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_poetcomments',
            },
        ),
        migrations.CreateModel(
            name='tbl_PoetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('competitionname', models.CharField(max_length=100)),
                ('poettitle', models.CharField(max_length=100)),
                ('poetimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('poetimageurl', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('likes', models.IntegerField(null=True)),
                ('comments', models.IntegerField(null=True)),
                ('share', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('posttype', models.CharField(max_length=100, null=True)),
                ('poststatus', models.CharField(max_length=100, null=True)),
                ('conpetitionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_CompetitionDetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement_App.tbl_Accountholders')),
            ],
            options={
                'db_table': 'tbl_poetdetails',
            },
        ),
        migrations.CreateModel(
            name='tbl_WinnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptname', models.CharField(max_length=100)),
                ('compttitle', models.CharField(max_length=100, null=True)),
                ('comptdesc', models.CharField(max_length=500, null=True)),
                ('posttile', models.CharField(max_length=100)),
                ('postdesc', models.CharField(max_length=500, null=True)),
                ('postimageurl', models.CharField(max_length=200, null=True)),
                ('winnername', models.CharField(max_length=100)),
                ('prizenumber', models.CharField(max_length=100, null=True)),
                ('likes', models.CharField(max_length=100, null=True)),
                ('views', models.CharField(max_length=100, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('share', models.CharField(max_length=100, null=True)),
                ('postdate', models.CharField(max_length=100, null=True)),
                ('rewarddate', models.CharField(max_length=100, null=True)),
                ('rewardamount', models.IntegerField(null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('comptid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_CompetitionDetails')),
                ('postid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_PoetDetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement_App.tbl_Accountholders')),
            ],
            options={
                'db_table': 'tbl_winnertdetails',
            },
        ),
        migrations.AddField(
            model_name='tbl_poetcomments',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement_App.tbl_PoetDetails'),
        ),
        migrations.AddField(
            model_name='tbl_poetcomments',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_Accountholders'),
        ),
        migrations.AddField(
            model_name='tbl_paymentdetails',
            name='postid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_PoetDetails'),
        ),
        migrations.AddField(
            model_name='tbl_paymentdetails',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_Accountholders'),
        ),
        migrations.AddField(
            model_name='tbl_complaintdetails',
            name='postid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement_App.tbl_PoetDetails'),
        ),
    ]
