# Generated by Django 2.1.4 on 2018-12-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
    ]
