# Generated by Django 2.1.4 on 2018-12-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
