# Generated by Django 2.1.4 on 2018-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_employee', '0002_auto_20181227_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofdays', models.IntegerField(max_length=100)),
                ('fromdate', models.DateField(max_length=100)),
                ('todate', models.DateField()),
                ('reason', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'leave_table',
            },
        ),
    ]
