# Generated by Django 2.1.4 on 2018-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181218_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
