# Generated by Django 2.1.4 on 2018-12-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees',
        ),
    ]
