# Generated by Django 2.1.4 on 2018-12-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='paidfees',
            field=models.BinaryField(null=True),
        ),
    ]
