# Generated by Django 2.1.4 on 2018-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_fees_paidfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='paidfees',
            field=models.BooleanField(null=True),
        ),
    ]
