# Generated by Django 2.1.4 on 2018-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181218_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='paidby',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='termtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
