# Generated by Django 2.1.4 on 2018-12-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Illness', models.CharField(max_length=100)),
                ('TreatedBy', models.CharField(max_length=100)),
                ('BillAmount', models.IntegerField(max_length=100)),
                ('PaidOn', models.DateField(max_length=100)),
                ('Insurance', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'hospitaldb',
            },
        ),
    ]
