# Generated by Django 2.1.4 on 2018-12-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Patientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='patientdb.patient'),
            preserve_default=False,
        ),
    ]
