# Generated by Django 2.1.4 on 2018-12-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenthpercentage', models.IntegerField(max_length=100)),
                ('twelfthpercentage', models.IntegerField(max_length=100)),
                ('ugpercentage', models.IntegerField(max_length=100)),
                ('pgpercentage', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'qualification_table',
            },
        ),
        migrations.CreateModel(
            name='senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'senior_table',
            },
        ),
        migrations.AddField(
            model_name='qualification',
            name='seniorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='tenant_senior.senior'),
        ),
    ]
