# Generated by Django 2.1.4 on 2018-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('directorname', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
                ('cinematography', models.CharField(max_length=100)),
                ('producedby', models.CharField(max_length=10)),
                ('releasedate', models.DateField()),
            ],
            options={
                'db_table': 'movie_table',
            },
        ),
    ]
