# Generated by Django 2.1.4 on 2018-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=100)),
                ('DOB', models.DateField(null=True)),
                ('Sex', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('SpouseName', models.CharField(max_length=100, null=True)),
                ('ContactNumber', models.IntegerField(max_length=20)),
            ],
            options={
                'db_table': 'patientbase',
            },
        ),
    ]
